title: "Heather Miller"
baseurl: ""

first-name: 'Heather'
last-name: 'Miller'
job-title: 'Computer Science PhD Student at <a href="http://ic.epfl.ch/">EPFL</a>'
blurb-about-self: 'Advisor: <a style="font-weight: bold;" href="http://lampwww.epfl.ch/~odersky/">Martin Odersky</a>'
profpic: '/resources/img/profilepic.png'
profpic-retina: '/resources/img/profilepic@2x.png'
twitter: heathercmiller
email: 'heather.miller@epfl.ch'
github: 'heathermiller'
location: 'EPFL, INR 329, Lausanne Switzerland'
location-url: "https://www.google.com/maps/place/46%C2%B031'06.3%22N+6%C2%B033'44.6%22E/@46.5188495,6.5633963,18z/data=!4m2!3m1!1s0x0:0x0"

# <a href="http://scala-lang.org">Scala programming language</a> with Professor
# . Language support for distributed and concurrent programming.
# <a href="http://www.nsfgrfp.org/">US NSF Graduate Research Fellow</a> and PhD student working on the Scala programming language with Professor Martin Odersky.